@startuml api_test_sync

skinparam participant {
    backgroundColor<<test>> Aqua
    backgroundColor<<api>> Orange
}

participant "Service" as S <<api>>
participant "Tests" as F <<test>>

F -> S: Requesting new ID\nGET /id
activate S #Orange

S -> F: Providing new ID\n200 { id: "seqN" }
deactivate S

@enduml
